### ISSUE TITLE
Wrong witness generated with c with integer division

### ISSUE THREAD

**Issue by Dimo99** [iden3/circom#103]
```
pragma circom 2.0.3;

template Hash() {
  signal output out;
  out <== 256 \ 256;
}

component main = Hash();

```
When I generate the witness for this circuit with wasm. I get the correct result witness with ["1","1"]. But when I generate it with c, the value is zero ["1", "0"].

**Comment by Dimo99** [comment]
This holds true for any other operation. And is valid also for circom 2.0.6
For example
```
pragma circom 2.0.6;

template Hash() {
  signal output out;
  out <== 256 + 256;
}

component main = Hash();
```
C witness output for this circuit is 
```
[
 "1",
 "0"
]
```
while wasm witness is correctly 
```
[
 "1",
 "512"
]
```

**Comment by clararod9** [comment]
We studied your examples and the issue is not with the C operations, it is related to the execution of main components that do not have any inputs. We had not considered that corner case and were not executing the circuit at all, this is the reason why it was always returning 0. We have just pushed a commit solving it, thank you for reporting the issue!
