### ISSUE TITLE
Non quadratic constraints are not allowed!

### ISSUE THREAD

**Issue by Apexlq** [iden3/circom#161]
I wanted to write a zero-knowledge proof that the linear regression was computed correctly, but the error "Non quadratic constraints are not allowed!" But isn't this expression linear?

My source code is as follows:
`pragma` circom 2.1.4; 

template linear() {
   signal input X[30];
   signal input y[30];
   signal mid;
   var lr = 1/10000;
   var w = -1/10;
   var b = 3;
   var y_hat;
   var det_w;
   var det_b;
   var temp;
   signal output w_result;
   signal output b_result;
 
   var X_train[30];
   var y_train[30];
   var epoches = 100;
   for(var i=0;i<30;i++){
       X_train[i] = X[i];
       y_train[i] = y[i];
   }
   
   for(var i = 0;i < epoches;i++){
      var sum_w = 0;
      var sum_b = 0;
      for(var j= 0;j<30;j++){
         y_hat = w * X_train[j] + b ;
         temp = y_train[j] - y_hat;
         sum_w = temp * (-X_train[j]) + sum_w;
         sum_b = temp * (-1) + sum_b;
      }
   det_w = 2 * sum_w;
   det_b = 2 * sum_b;
   w =  w - lr * det_w;
   b =  b - lr * det_b;
   }
   w_result <== w;
   b_result <== b;
}
component main = `linear();`

The compiler error is as follows，
![image](https://user-images.githubusercontent.com/115442237/224686119-251f45d4-3788-4195-881a-bda561c6f1af.png)

**Comment by alrubio** [comment]
You have to understand the difference between var and signal in circom. When building constraints a var stores an expression over signals, so you cannot use vars to split a constraint which is not constraint in R1CS format into several that are in R1CS format. To do so, you need to introduce auxiliary signals instead of vars.
In your program w takes a complex expression and as a result the instruction 
w_result <== w;
generates a non-quadratic constraint (being precise a constraint that is not in R1CS format).
To solve this in your code, you may need to define two matrices of signals:

signal y_hat[epoches][30];  // instead of the var y_hat
signal sum_aux[epoches][30];

and write the inner for loop as:
    for(var j= 0;j<30;j++){
        y_hat[i][j] <== w * X[j] + b ;   // X_train is not needed
        temp = y[j] - y_hat[i][j];  // y_train is not needed
	sum_aux[i][j] <== temp * (-X[j]);
        sum_w = sum_aux[i][j] + sum_w;
        sum_b = temp * (-1) + sum_b;
    }
This way the expressions sum_w and sum_b keep being a linear expression over signals and so is w in the outer loop and all added constraints are quadratic (in R1CS form).

**Comment by Apexlq** [comment]
Thank you very much for your help@alrubio.
