### ISSUE TITLE
"previous errors were found"

### ISSUE THREAD

**Issue by Yijia-Chen** [iden3/circom#18]
When I compile my circuits, if there is an error, there is always a line in the error message which says "previous errors were found". Is it possible to eventually expand that error message to point to which previous errors?

**Comment by alrubio** [comment]
Maybe your error is related to a recent problem we have solved. The problem was that the initial memory assigned in the wasm code was unnecessarily large, and this was generating an internal error that was not caught by the compiler. 
Now we are assigning tight initial memory and we are catching errors in the final wasm generation if they appear.
Update the sources and recompile circom and let me know if the problem is solved.
