### ISSUE TITLE
Question: Why is <== considered safer than <-- ?

### ISSUE THREAD

**Issue by MartinLoeper** [iden3/circom#23]
The docs [1] state that "using `<--` and `-->` is, in general, dangerous". Could someone please elaborate on the reason behind this statement?
Is it "safer" to use `<==` instead of `<--` followed by `===`?
Some students in crypto class (myself included) are curious about this. :nerd_face: 

[1] https://github.com/iden3/circom/blob/86a20b04488d122d27b4c720650ff7fd11a6c2a1/mkdocs/docs/circom-language/signals.md?plain=1#L104

**Comment by alrubio** [comment]
Regarding constraints, writing 
x <-- E; x === E; (for some E that is a proper quadratic expression)
is equivalent to x<== E,
So if you write it like this, both are safe, but the second option is shorter (this is the nice property of circom's <==).
Moreover, regarding the wasm or C++ code generated, using x<--E; x === E; is a bit less efficient than using x <== E; since the use of === introduces an assert that is checked in execution time.
Therefore, there is no reason to use <-- followed by ===, instead of <== (when possible).
The reason why we say that using <== is safer than combinations of <-- and ==  is because we assume that what is done using <-- and what is written using === is syntactically different and hence it is the programmer responsibility to be sure that both versions say the same. 
In particular, using <-- just describes how to compute the values of the signals but adds no constraint, and hence it does not provide a definition of the circuit (which is made by means of quadratic constraints). Using <== ensures both that we know how to compute the signal, but also we add a constraint that describes this relation in the circuit. 
Therefore, the only reason to use <-- is when the way to efficiently compute a signal from the other signals cannot be expressed with quadratic expressions. If so, we use <-- , but then we need to find equations E1 === E2 that express the same relation as quadratic constraints, so that we have both a definition of the circuit (by means of constraints) and an efficient way to compute the signals that are equivalent.
In general, if your circuit is made combining circuits from the circomlib, using <== is enough and so you are in the safe side as the circuit described by the R1CS constraints and the computation of the signals (as wasm or C++ code) are guaranteed to be the same.
Let me know if this clarifies a bit our claims and just tell me if more explanations are needed. 
Understanding the semantics of <==, <-- and === is the key for using circom appropriately.

**Comment by MartinLoeper** [comment]
That makes perfectly sense. Thanks so much for the explanation! Going to write some circuits over the next couple of days to learn more about this. =)

**Comment by ezhangTribalScale** [comment]
Could you give an example that using <--  and ===, or only <-- without constraint, will cause problems? I still don't understand why constraint is needed.

**Comment by MarkuSchick** [comment]
> Could you give an example that using <-- and ===, or only <-- without constraint, will cause problems? I still don't understand why constraint is needed.

Hey @ezhangTribalScale, here is an good reference I found
 https://github.com/0xPARC/zk-bug-tracker#8-assigned-but-not-constrained
