### ISSUE TITLE
Does --wasm switch work?

### ISSUE THREAD

**Issue by ddengster** [iden3/circom#39]
`circom2 circuits/c.circom --r1cs --wasm --sym --c ` does not spit out a wasm file. The best error message I could find is `previous errors were found`. Is this part working at all?

According to https://twitter.com/railgun_project/status/1500966895733850117 they've also had problems that they had to put out a bounty for it.

Also I don't have the best experience working with circom2, a lot of documentation's outdated, makes me sad:(

**Comment by 3093sw** [comment]
I don't think the --wasm switch works. I've tried a couple of times. Does C++ make work for you?

**Comment by alrubio** [comment]
The --wasm switch works if there are no previous errors in the compilation (like in all compilers) and if you get 
"previous errors were found"
it means that there are errors in your code.
Can you provide a link to the code you are compiling to check why you are not getting a better error message (explaining the reason for the error)?
Thanks
Regarding the documentation, you have to follow the documentation included in this git. If you find outdated documentation here please let us know, and we will correct it.

**Comment by ddengster** [comment]
> The --wasm switch works if there are no previous errors in the compilation (like in all compilers) and if you get "previous errors were found" it means that there are errors in your code. Can you provide a link to the code you are compiling to check why you are not getting a better error message (explaining the reason for the error)? Thanks Regarding the documentation, you have to follow the documentation included in this git. If you find outdated documentation here please let us know, and we will correct it.

I'm using windows, but the instructions seem to be for linux. I'm guessing circom2 is mostly tested only on linux? Anyway, I improvised.

I had circom installed via npm but determined that the errors were coming from `#pragma circom 2.0.0` line (i could compile code samples without that line), so I switched to using circom2 installed via npm and ran into the errors in the original post. 

In any case I've switched to an alternative for now.

**Comment by alrubio** [comment]
It seems that since you have installed circom via npm, either you have installed the old circom (version 0.5.x, that was written in JavaScript) or you have installed Circom 2.0 WASM which is developed by another team using the circom 2.0.x sources (written in Rust) that you have in this git.
If you are using circom 0.5 there are several things (like the #pragma circom 2.0.0) of the new version 2.0 that are not compatible, so you'll get errors and you cannot follow the documentation given here (look at the "Important deprecation note" given in the initial README of this git). If you are using Circom 2.0 WASM and something is not working well you may ask the developers to see if the problems comes form their side (you can go to their git from the npm page https://www.npmjs.com/package/circom2/v/0.1.0).
Regarding the installation of circom 2.0 described in the documentation provided in this git, it has not been made for windows (it's been tested for linux and macos). In any case, since you have the sources available, if at some point you want to try to make it work on windows you have to adapt the installation description given in  https://docs.circom.io/getting-started/installation/ to the windows environment: installing rust, downloading the sources from this git and compiling the sources with rust to generate an executable for circom.
If there are no further comments I will proceed to close this issue.
