### ISSUE TITLE
Exit with message when circuit too large for wasm

### ISSUE THREAD

**Issue by jonathanpwang** [iden3/circom#41]
For circuits larger than ~1M constraints, it would be helpful if the witness generation exited with error when it detects a proof that is too large for wasm, and suggests compiling in C++ instead.

**Comment by alrubio** [comment]
Which version of node do you have? In general, the witness generation may work even with quite larger circuits than ~1M constraints.
Form your message I understand that the error occurs when generating the witness with the JS and wasm provided by circom and not when generating the proof with snarkjs (just to be sure).

**Comment by jonathanpwang** [comment]
Node version 16. Yes we were able to do witness generation on some larger circuits, but our final circuit was 25M constraints so wasm did not work. Jordi told us to add a request for an error message at runtime. 
And yes, this is for the generation of witness with JS and wasm provided by circom, not the proof generation with snarkjs.

**Comment by alrubio** [comment]
Right, this sounds more like my experience. I got confused because you said ~1M constraints. So I thought you had problems with smaller circuits.
I understand that you would like to have the JS witness generation to provide the error message (and the suggestion to use --c) either if the initial memory is already too large or if, when computing the witness, wasm runs out-of-memory.
If so we will add it soon together with another change in the produced JS.
I don't want to add the check of the initial memory size in the compiler, because that limit will eventually change.

**Comment by jonathanpwang** [comment]
Yes this sounds great - thanks so much! And I agree no need to check in the compiler, just the JS.

**Comment by alrubio** [comment]
I've added the check in the branch **adding_checks_to_js_and_c** together with other changes related to the input signal setting part. Yo can see it at the beginning of **code_producers/src/wasm_elements/witness_calculator.js**
Now when  WebAssembly.compile fails in addition to the error message it prints
Try to run circom --c in order to generate c++ code instead
Is this what you expected?
I plan to merge this branch early next week.

**Comment by jonathanpwang** [comment]
Yes, this is exactly what I wanted. Thank you very much!
